apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-volume-1
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: es-volume-1
    volumeAttributes:
      source: "//192.168.1.197/ElasticSearchVolumes/es1"
    nodeStageSecretRef:
      name: elasticsearch-secrets
      namespace: es
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-volume-2
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: es-volume-2
    volumeAttributes:
      source: "//192.168.1.197/ElasticSearchVolumes/es2"
    nodeStageSecretRef:
      name: elasticsearch-secrets
      namespace: es
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-volume-3
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: es-volume-3
    volumeAttributes:
      source: "//192.168.1.197/ElasticSearchVolumes/es3"
    nodeStageSecretRef:
      name: elasticsearch-secrets
      namespace: es

